services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    branch: main
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:0ZXbdHVIYMYGb1h0FOs/n38zif80H5pAeZAlwM3hU9w=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://api-rest-laravel-8-jwt.onrender.com

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-east-2.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.vcovenbrjegwzxmelxqp
      - key: DB_PASSWORD
        value: 0LastPassSuPa1.

      - key: JWT_SECRET
        value: wJzgzbLqmlp46Huo3XhFWReQPjduDy17DOG2q3LvmMg7iBlaavm3UTWWoxfLbjJ1

      # Swagger config para Render
      - key: L5_SWAGGER_CONST_HOST
        value: https://api-rest-laravel-8-jwt.onrender.com
      - key: L5_SWAGGER_UI_DOC_EXPANSION
        value: list
