name: Deploy Laravel App to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug deploy URL (no imprime valor real)
        run: echo "Triggering deploy..."

      - name: Trigger Deploy Hook
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
